version: '2.2'
services:
  reflex-api:
    image: reflex-api:latest
    env_file:
      - ./local.env
    environment:
      - FLASK_CONFIG=production
    container_name: reflex-api
    volumes:
      - ./instance/application.conf:/instance/application.conf
    ports:
      - "80:80"
    networks:
      - elastictest

networks:
  elastictest:
    name: es_elastictest
    external: true