"""empty message

Revision ID: 01510000707f
Revises: 2cedec1413c9
Create Date: 2020-09-24 21:42:20.718248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01510000707f'
down_revision = '2cedec1413c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('close_reason',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by_uuid', sa.String(), nullable=True),
    sa.Column('organization_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('close_reason')
    # ### end Alembic commands ###
