"""empty message

Revision ID: 08b93d0d90c1
Revises: 
Create Date: 2020-08-22 22:42:14.884870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b93d0d90c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('auth_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('credential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('add_user', sa.Boolean(), nullable=True),
    sa.Column('update_user', sa.Boolean(), nullable=True),
    sa.Column('delete_user', sa.Boolean(), nullable=True),
    sa.Column('add_user_to_role', sa.Boolean(), nullable=True),
    sa.Column('remove_user_from_role', sa.Boolean(), nullable=True),
    sa.Column('reset_user_password', sa.Boolean(), nullable=True),
    sa.Column('unlock_user', sa.Boolean(), nullable=True),
    sa.Column('view_users', sa.Boolean(), nullable=True),
    sa.Column('add_role', sa.Boolean(), nullable=True),
    sa.Column('update_role', sa.Boolean(), nullable=True),
    sa.Column('delete_role', sa.Boolean(), nullable=True),
    sa.Column('set_role_permissions', sa.Boolean(), nullable=True),
    sa.Column('view_roles', sa.Boolean(), nullable=True),
    sa.Column('add_playbook', sa.Boolean(), nullable=True),
    sa.Column('update_playbook', sa.Boolean(), nullable=True),
    sa.Column('delete_playbook', sa.Boolean(), nullable=True),
    sa.Column('view_playbooks', sa.Boolean(), nullable=True),
    sa.Column('add_tag_to_playbook', sa.Boolean(), nullable=True),
    sa.Column('remove_tag_from_playbook', sa.Boolean(), nullable=True),
    sa.Column('add_tag', sa.Boolean(), nullable=True),
    sa.Column('update_tag', sa.Boolean(), nullable=True),
    sa.Column('delete_tag', sa.Boolean(), nullable=True),
    sa.Column('view_tags', sa.Boolean(), nullable=True),
    sa.Column('add_credential', sa.Boolean(), nullable=True),
    sa.Column('update_credential', sa.Boolean(), nullable=True),
    sa.Column('decrypt_credential', sa.Boolean(), nullable=True),
    sa.Column('delete_credential', sa.Boolean(), nullable=True),
    sa.Column('view_credentials', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('playbook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('user_uuid', sa.String(length=100), nullable=True),
    sa.Column('refresh_token', sa.String(length=200), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['permissions_uuid'], ['permission.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tag_playbook',
    sa.Column('playbook_uuid', sa.String(), nullable=True),
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['playbook_uuid'], ['playbook.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('role_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_uuid'], ['role.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tag_playbook')
    op.drop_table('role')
    op.drop_table('tag')
    op.drop_table('refresh_token')
    op.drop_table('playbook')
    op.drop_table('permission')
    op.drop_table('credential')
    op.drop_table('auth_token_blacklist')
    # ### end Alembic commands ###
