"""empty message

Revision ID: 08c7c08f8de8
Revises: 6e100141093c
Create Date: 2020-09-24 22:01:25.457280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c7c08f8de8'
down_revision = '6e100141093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'merged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('merged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
