"""empty message

Revision ID: 26a6a5e2bc85
Revises: f8c5c7303975
Create Date: 2020-09-26 23:56:14.520864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a6a5e2bc85'
down_revision = 'f8c5c7303975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_rule', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('event_rule', sa.Column('created_by_uuid', sa.String(), nullable=True))
    op.add_column('event_rule', sa.Column('organization_uuid', sa.String(), nullable=True))
    op.add_column('event_rule', sa.Column('updated_by_uuid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'event_rule', 'organization', ['organization_uuid'], ['uuid'])
    op.create_foreign_key(None, 'event_rule', 'user', ['updated_by_uuid'], ['uuid'])
    op.create_foreign_key(None, 'event_rule', 'user', ['created_by_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_rule', type_='foreignkey')
    op.drop_constraint(None, 'event_rule', type_='foreignkey')
    op.drop_constraint(None, 'event_rule', type_='foreignkey')
    op.drop_column('event_rule', 'updated_by_uuid')
    op.drop_column('event_rule', 'organization_uuid')
    op.drop_column('event_rule', 'created_by_uuid')
    op.drop_column('event_rule', 'active')
    # ### end Alembic commands ###
