"""empty message

Revision ID: 4931393881c2
Revises: 95b73f216814
Create Date: 2020-09-24 00:28:49.923219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4931393881c2'
down_revision = '95b73f216814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('agent_pairing_token_valid_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'agent_pairing_token_valid_minutes')
    # ### end Alembic commands ###
