"""empty message

Revision ID: 4950b7862ad9
Revises: 5e5ca60a5ad0
Create Date: 2020-09-25 14:38:58.343554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4950b7862ad9'
down_revision = '5e5ca60a5ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'signature')
    # ### end Alembic commands ###
