"""empty message

Revision ID: 5e5ca60a5ad0
Revises: 08c7c08f8de8
Create Date: 2020-09-25 07:42:22.233716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5ca60a5ad0'
down_revision = '08c7c08f8de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by_uuid', sa.String(), nullable=True))
    op.add_column('event', sa.Column('updated_by_uuid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['created_by_uuid'], ['uuid'])
    op.create_foreign_key(None, 'event', 'user', ['updated_by_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'updated_by_uuid')
    op.drop_column('event', 'created_by_uuid')
    # ### end Alembic commands ###
