"""empty message

Revision ID: 6e100141093c
Revises: f45b9607a883
Create Date: 2020-09-24 21:57:52.986925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e100141093c'
down_revision = 'f45b9607a883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('merged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'merged')
    # ### end Alembic commands ###
