"""empty message

Revision ID: 88ccc325f8c8
Revises: a64c4f7b8f70
Create Date: 2020-09-18 22:38:40.809642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ccc325f8c8'
down_revision = 'a64c4f7b8f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('require_case_templates', sa.Boolean(), nullable=True),
    sa.Column('email_from', sa.String(), nullable=True),
    sa.Column('email_server', sa.String(), nullable=True),
    sa.Column('email_secret_uuid', sa.String(), nullable=True),
    sa.Column('allow_comment_deletion', sa.Boolean(), nullable=True),
    sa.Column('playbook_action_timeout', sa.Integer(), nullable=True),
    sa.Column('playbook_timeout', sa.Integer(), nullable=True),
    sa.Column('logon_password_attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_secret_uuid'], ['credential.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('modified_at', sa.DATETIME(), nullable=True),
    sa.Column('base_url', sa.VARCHAR(), nullable=True),
    sa.Column('require_case_templates', sa.BOOLEAN(), nullable=True),
    sa.Column('email_from', sa.VARCHAR(), nullable=True),
    sa.Column('email_server', sa.VARCHAR(), nullable=True),
    sa.Column('email_secret_uuid', sa.VARCHAR(), nullable=True),
    sa.Column('allow_comment_deletion', sa.BOOLEAN(), nullable=True),
    sa.Column('playbook_action_timeout', sa.INTEGER(), nullable=True),
    sa.Column('playbook_timeout', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('allow_comment_deletion IN (0, 1)'),
    sa.CheckConstraint('require_case_templates IN (0, 1)'),
    sa.ForeignKeyConstraint(['email_secret_uuid'], ['credential.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('global_settings')
    # ### end Alembic commands ###
