"""empty message

Revision ID: 8e11ee8e0e64
Revises: bbdcf06708e0
Create Date: 2020-08-26 00:39:35.663499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e11ee8e0e64'
down_revision = 'bbdcf06708e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('raw_log', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'raw_log')
    # ### end Alembic commands ###
