"""empty message

Revision ID: a64c4f7b8f70
Revises: dfc15f8b47ce
Create Date: 2020-09-18 22:07:08.036630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64c4f7b8f70'
down_revision = 'dfc15f8b47ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('failed_logons', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'failed_logons')
    # ### end Alembic commands ###
