"""empty message

Revision ID: f45b9607a883
Revises: 51cad272d821
Create Date: 2020-09-24 21:57:07.136630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45b9607a883'
down_revision = '51cad272d821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('close_reason_uuid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'case', 'close_reason', ['close_reason_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_column('case', 'close_reason_uuid')
    # ### end Alembic commands ###
