"""empty message

Revision ID: f8c5c7303975
Revises: 4950b7862ad9
Create Date: 2020-09-26 23:54:21.127119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c5c7303975'
down_revision = '4950b7862ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_signature', sa.String(), nullable=True),
    sa.Column('rule_signature', sa.String(), nullable=True),
    sa.Column('target_case_uuid', sa.String(), nullable=True),
    sa.Column('merge_into_case', sa.Boolean(), nullable=True),
    sa.Column('dismiss', sa.Boolean(), nullable=True),
    sa.Column('expire', sa.Boolean(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('observable_event_rule',
    sa.Column('observable_uuid', sa.String(), nullable=True),
    sa.Column('event_rule_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_rule_uuid'], ['event_rule.uuid'], ),
    sa.ForeignKeyConstraint(['observable_uuid'], ['observable.uuid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observable_event_rule')
    op.drop_table('event_rule')
    # ### end Alembic commands ###
